name: Demo
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'get tag version'
        required: true
        default: '0.0.1'
jobs:
  push_to_registry:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create env file
        run: |
          cat << EOF > .env
          VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}
          VUE_APP_TAG=${{ github.event.inputs.tag }}
          EOF
          cat .env
          pwd
          ls
          
